apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  serviceName: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: loki-sa
      containers:
      - name: loki
        image: docker.io/grafana/loki:{LOKI_VERSION}
        imagePullPolicy: "IfNotPresent"
        args:
          - "-config.file=/etc/loki/loki.yaml"
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 400m
            memory: 3000Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /loki
        - name: config
          mountPath: /etc/loki/loki.yaml
          subPath: loki.yaml
        #- name: alert
        #  mountPath: /loki/scratch/rules.yml
        #  subPath: rules.yml
      terminationGracePeriodSeconds: 4800
      volumes:
      - name: config
        configMap:
          name: loki-config
      #- name: alert
      #  configMap:
      #    name: loki-rule
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: loki
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {STORAGECLASS_NAME}
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false

    ingester:
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_retain_period: 30s
      max_transfer_retries: 0
      wal:
        enabled: false
      lifecycler:
        address: 0.0.0.0
        ring:
          replication_factor: 1
          kvstore:
            store: inmemory
        final_sleep: 0s

    querier:
      max_concurrent: 2048
      query_ingesters_within: 0
      query_timeout: 5m

    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    limits_config:
      retention_period: 168h # 7d
      #retention_stream:
      #- selector: '{namespace=""}' or '{pod_name=""}'
      #  priority: 1
      #  period: 24h ## 최소 설정 가능 기간 24h
      enforce_metric_name: false
      #reject_old_samples: true
      #reject_old_samples_max_age: 72h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      max_query_series: 100000
      per_stream_rate_limit: 512mb
      per_stream_rate_limit_burst: 1024mb

    schema_config:
      configs:
      - from: 2022-07-10
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
      http_server_read_timeout: 5m
      http_server_write_timeout: 5m
      
     # grpc_server_max_recv_msg_size:
     # grpc_server_max_send_msg_size:
     # log_level:

    #grpc_client_config:
    #  max_recv_msg_size:
    #  max_send_msg_size:

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    chunk_store_config:
      max_look_back_period: 168h # 7d
    
    compactor:
      retention_enabled: true
      retention_delete_delay: 30m
      working_directory: /loki/compactor
      shared_store: filesystem
      
    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/scratch
      alertmanager_url: http://alertmanager-main.monitoring.svc:9093
      wal:
        dir: /loki/wal
      ring:
        kvstore:
          store: inmemory
      enable_api: true
      enable_alertmanager_v2: true
